server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ha?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#fw:
#  mvc:
#    load-default-config: 'false'
#
#logging:
#  level:
#    root: INFO
